name: Mypy

on: [ push ]

jobs:
  mypy:
    steps:
      - uses: jpetrucciani/mypy-check@master
        with:
          requirements_file: 'requirements.txt'
          python_version: '3.11'
