name: Pylint

on: [ push ]

jobs:
  pylint-checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --rcfile=$(git ls-files '.pylintrc') --extension-pkg-whitelist=pydantic
